# Generated by Django 3.2.15 on 2022-08-28 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=256)),
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1154)])),
                ('types', models.JSONField()),
                ('stats', models.JSONField()),
            ],
        ),
    ]
